
on:
  workflow_dispatch:
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Install tools
          run: |
            sudo apt-get update
            sudo apt-get install -y openjdk-8-jdk
            sudo apt-get install -y maven
        - name: Install dependencies
          run: |
            mvn install
        - name: Build
          run: |
            mvn package
